In [49]:
import gym

import mdptoolbox, mdptoolbox.example

import time

import numpy as np

In [117]:
env = gym.make('FrozenLake-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()


SFFF
FHFH
FFFH
HFFG
0
  (Right)
SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
1
  (Down)
SFFF
FHFH
FFFH
HFFG
0
  (Down)
SFFF
FHFH
FFFH
HFFG
0
  (Right)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Down)
SFFF
FHFH
FFFH
HFFG
4
  (Down)
SFFF
FHFH
FFFH
HFFG
4
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
4
Episode finished after 12 timesteps

SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
4
  (Left)
SFFF
FHFH
FFFH
HFFG
8
  (Left)
SFFF
FHFH
FFFH
HFFG
4
  (Left)
SFFF
FHFH
FFFH
HFFG
4
  (Right)
SFFF
FHFH
FFFH
HFFG
8
  (Left)
SFFF
FHFH
FFFH
HFFG
8
Episode finished after 7 timesteps

SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Down)
SFFF
FHFH
FFFH
HFFG
1
  (Up)
SFFF
FHFH
FFFH
HFFG
1
  (Up)
SFFF
FHFH
FFFH
HFFG
1
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Right)
SFFF
FHFH
FFFH
HFFG
4
  (Left)
SFFF
FHFH
FFFH
HFFG
4
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Right)
SFFF
FHFH
FFFH
HFFG
4
  (Left)
SFFF
FHFH
FFFH
HFFG
0
 

MDP Toolbox Example
https://pymdptoolbox.readthedocs.io/en/latest/api/mdp.html


- Creates transition probability P, size (Action X State X State)
- Creates Reward Matrix R, size (State X Action)
- Action is either WAIT (Action = 0) or CUT (Action = 1). There is some probability p that the fire burns the forest. 
- The states of the forest are the ages of how old the forest is since last cut or burn, where S = {0, 1, ..., S-1}
- 

In [5]:
# https://pymdptoolbox.readthedocs.io/en/latest/api/mdp.html

import mdptoolbox, mdptoolbox.example

#P, R = mdptoolbox.example.forest()
P, R = mdptoolbox.example.forest(S = 3, r1 = 4, r2 = 2, p = 0.1, is_sparse = False)

- S: The number of states, the number of years old the forest can be 
- r1: the reward when the forest is in its oldest state and action WAIT is performed 
- r2: the reward whne the forest is in its oldest state and action CUT is performed
- p: the probability that a wild fire occurs 

In [6]:
P

array([[[0.1, 0.9, 0. ],
        [0.1, 0. , 0.9],
        [0.1, 0. , 0.9]],

       [[1. , 0. , 0. ],
        [1. , 0. , 0. ],
        [1. , 0. , 0. ]]])

In [7]:
# Probability that if we take action 0, in a given state, which state we land in
P[0, :, :] 

array([[0.1, 0.9, 0. ],
       [0.1, 0. , 0.9],
       [0.1, 0. , 0.9]])

In [8]:
# Probability that if we take action 0, in a given state, which state we land in
P[1, :, :]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [9]:
R

array([[0., 0.],
       [0., 1.],
       [4., 2.]])

In [10]:
# If in a state, and take action 0, what is our reward
R[:, 0]

array([0., 0., 4.])

In [11]:
# If in the state, and take action 1, what is our reward
R[:, 1]

array([0., 1., 2.])

In [12]:
Psp, Rsp = mdptoolbox.example.forest(is_sparse=True)

len(Psp)

2

In [13]:
Psp[0]

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [14]:
Psp[1]

<3x3 sparse matrix of type '<class 'numpy.longlong'>'
	with 3 stored elements in Compressed Sparse Row format>

In [15]:
Rsp

array([[0., 0.],
       [0., 1.],
       [4., 2.]])

The Sparse representation of P and R is identical to the non sparse version

In [16]:
(Psp[0].todense() == P[0]).all()

True

In [17]:
(Rsp == R).all()

True

Use Policy Iteration on the Forest MDP
https://pymdptoolbox.readthedocs.io/en/latest/api/mdp.html

In [18]:
pi = mdptoolbox.mdp.PolicyIteration(P, R, 0.9) # P = Transitions, R = Reward, 0.9 = Discount 
pi.run()

expected = (26.244000000000014, 29.484000000000016, 33.484000000000016)
all(expected[k] - pi.V[k] < 1e-12 for k in range(len(expected)))

True

In [19]:
pi.policy

(0, 0, 0)

In [20]:
pi = mdptoolbox.mdp.PolicyIteration(P, R, 0.2) # P = Transitions, R = Reward, 0.9 = Discount 
pi.run()

expected = (26.244000000000014, 29.484000000000016, 33.484000000000016)
all(expected[k] - pi.V[k] < 1e-12 for k in range(len(expected)))

pi.policy

(0, 1, 0)

Use Value Iteration on the Forest MDP https://pymdptoolbox.readthedocs.io/en/latest/api/mdp.html

In [21]:
vi = mdptoolbox.mdp.ValueIteration(P, R, 0.96)
vi.verbose

False

In [22]:
vi.run()

In [23]:
expected = (5.93215488, 9.38815488, 13.38815488)

all(expected[k] - vi.V[k] < 1e-12 for k in range(len(expected)))

vi.policy # Tuple shows which action maximizes the value in this state


(0, 0, 0)

In [24]:
vi.iter

4

Try 2 

In [25]:
vi = mdptoolbox.mdp.ValueIteration(P, R, 0.20) # Transition prob maatrix, reward matrix, then discount factor 
vi.verbose
vi.run()
print(vi.policy)
print(vi.iter)

(0, 1, 0)
3


#### Add more states to Random Forest

In [26]:
# https://pymdptoolbox.readthedocs.io/en/latest/api/mdp.html

import mdptoolbox, mdptoolbox.example

P, R = mdptoolbox.example.forest(S = 10, r1 = 4, r2 = 2, p = 0.1, is_sparse = False)

In [27]:
P

array([[[0.1, 0.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.1, 0. , 0.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.1, 0. , 0. , 0.9, 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.1, 0. , 0. , 0. , 0.9, 0. , 0. , 0. , 0. , 0. ],
        [0.1, 0. , 0. , 0. , 0. , 0.9, 0. , 0. , 0. , 0. ],
        [0.1, 0. , 0. , 0. , 0. , 0. , 0.9, 0. , 0. , 0. ],
        [0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0.9, 0. , 0. ],
        [0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.9, 0. ],
        [0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.9],
        [0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.9]],

       [[1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ,

In [28]:
R

array([[0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [4., 2.]])

##### Policy Iteration with bigger state amount

In [29]:
pi = mdptoolbox.mdp.PolicyIteration(P, R, 0.9) # P = Transitions, R = Reward, 0.9 = Discount 
pi.run()

expected = (26.244000000000014, 29.484000000000016, 33.484000000000016)
all(expected[k] - pi.V[k] < 1e-12 for k in range(len(expected)))

print("Optimal Policy",pi.policy)
print("Iters to Converge",pi.iter)


Optimal Policy (0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Iters to Converge 9


##### Value Iteration with bigger state amount

In [30]:
vi = mdptoolbox.mdp.ValueIteration(P, R, 0.90)
print(vi.verbose)
vi.run()

expected = (5.93215488, 9.38815488, 13.38815488)
all(expected[k] - vi.V[k] < 1e-12 for k in range(len(expected)))

print("Optimal Policy",vi.policy) # Tuple shows which action maximizes the value in this state
print("Iters to Converge:",vi.iter)

False
Optimal Policy (0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Iters to Converge: 16


##### Q Learning on Forest Problem

In [31]:
#P, R = mdptoolbox.example.forest(S = 10, r1 = 4, r2 = 2, p = 0.1, is_sparse = False)

ql = mdptoolbox.mdp.QLearning(P, R, 0.9)
ql.run()
#print(ql.Q)

print(ql.policy)

(0, 1, 1, 0, 1, 0, 0, 0, 0, 0)


##### Loop Through Different State Sizes and Compare Difference in Convergence Iterations

In [32]:
#state_size = [10, 100, 1000, 10000]
state_size = [5, 10, 20, 100, 1000]

for ss in state_size:
    
    P, R = mdptoolbox.example.forest(S = ss, r1 = 4, r2 = 2, p = 0.1, is_sparse = False)
    
    # Policy Iteration 
    pi = mdptoolbox.mdp.PolicyIteration(P, R, 0.9) # P = Transitions, R = Reward, 0.9 = Discount 
    pi.run()
    print()
    print("State size:", ss)
    #print("Optimal Policy",pi.policy)
    #print("Iters to Converge",pi.iter)
    #print("PI Time:",pi.time)
    #print(pi.V)
    #print(pi.policy)
    
    # Value Iteration 
    vi = mdptoolbox.mdp.ValueIteration(P, R, 0.9)
    vi.run()
    #print("Optimal Policy",vi.policy) # Tuple shows which action maximizes the value in this state
    #print("Iters to Converge:",vi.iter)
    #print("VI Time:",vi.time)
    #print(vi.V)
    #print(vi.policy)
    
    ql = mdptoolbox.mdp.QLearning(P, R, 0.9)
    ql.run()
    ql.Q
    #print(ql.V)
    #print(ql.policy)
    
    print("Did VI and PI Give the same policy?",vi.policy == pi.policy)
    print("QLearning and PI?",ql.policy == pi.policy)
    print("QLearning and VI",ql.policy == vi.policy)

    if pi.iter < vi.iter:
        print("PI requires fewer iterations to converge", pi.iter , " < ", vi.iter)
    else:
        print("VI requires fewer iterations to converge", vi.iter , " < ", pi.iter)
    
    if pi.time < vi.time:
        print("PI is faster to converge", pi.time , " < ", vi.time)
    else:
        print("VI is faster to converge", vi.time , " < ", pi.time)
    
    if pi.V[-1] > vi.V[-1]:
        print("PI has higher reward", pi.V[-1] , " > ", vi.V[-1])
    else:
        print("VI has higher reward", vi.V[-1] , " > ", pi.V[-1])
    print(pi.V[-1])
    print(vi.V[-1])
    print(ql.V[-1])

   


State size: 5
Did VI and PI Give the same policy? True
QLearning and PI? False
QLearning and VI False
PI requires fewer iterations to converge 4  <  6
VI is faster to converge 0.0004391670227050781  <  0.0028219223022460938
PI has higher reward 29.208852400000016  >  15.482564617000001
29.208852400000016
15.482564617000001
10.080001565104842

State size: 10
Did VI and PI Give the same policy? True
QLearning and PI? False
QLearning and VI False
PI requires fewer iterations to converge 9  <  16
VI is faster to converge 0.0008089542388916016  <  0.003010988235473633
PI has higher reward 23.89652993194315  >  21.664850965110947
23.89652993194315
21.664850965110947
3.332134772529941

State size: 20
Did VI and PI Give the same policy? True
QLearning and PI? False
QLearning and VI False
PI requires fewer iterations to converge 10  <  39
VI is faster to converge 0.0033452510833740234  <  0.004821062088012695
PI has higher reward 23.172433847048566  >  23.089675091923866
23.172433847048566
23.

#### Gridworld problem from Open Gym

- S: Initial State
- F: Frozen Lake
- H: Hole
- G: The Goal
- Red Square: Current Position

In [33]:
# Create the Frozen Lake Environment 
env = gym.make('FrozenLake-v0')

# Put into initial state
env.reset()

# Print the State
env.render()


SFFF
FHFH
FFFH
HFFG


In [40]:
print("Action space:", env.action_space)
n_actions = env.action_space.n
print("Actions:",n_actions)

print("Observation Space:",env.observation_space)
n_states = env.observation_space.n
print("Size:",n_states)

Action space: Discrete(4)
Actions: 4
Observation Space: Discrete(16)
Size: 16


In [154]:
# Dummy to randomly play Frozen Lake

MAX_ITERATIONS = 10
 
env = gym.make("FrozenLake-v0")
env.reset()
env.render()
for i in range(MAX_ITERATIONS):
    random_action = env.action_space.sample()
    new_state, reward, done, info = env.step(
       random_action)
    print(new_state)
    print(reward)
    print(done)
    #print(info)
    env.render()
    if done:
        break


SFFF
FHFH
FFFH
HFFG
0
0.0
False
  (Up)
SFFF
FHFH
FFFH
HFFG
4
0.0
False
  (Right)
SFFF
FHFH
FFFH
HFFG
8
0.0
False
  (Left)
SFFF
FHFH
FFFH
HFFG
9
0.0
False
  (Right)
SFFF
FHFH
FFFH
HFFG
5
0.0
True
  (Up)
SFFF
FHFH
FFFH
HFFG


https://learning.oreilly.com/library/view/reinforcement-learning-algorithms/9781789131116/ab06aa68-01f9-481e-94ac-4c6748c3b858.xhtml

In [155]:
env = gym.make("FrozenLake-v0")
#env.reset()
#env.render()
env = env.unwrapped

n_actions = env.action_space.n
print("Actions:",n_actions)

n_states = env.observation_space.n
print("Size:",n_states)

V = np.zeros(n_states)
policy = np.zeros(n_states)

Actions: 4
Size: 16


In [119]:
# Used in Policy Iteration and Value Iteration
def eval_state_action(V, s, a, gamma = 0.99):
    return np.sum([p* (rew + gamma*V[next_s]) for p, next_s, rew, _ in env.P[s][a]]) # env.P is a dictionary with info about enviroment

In [120]:
def policy_evaluation(V, policy, epsilon = 0.0001):
    while True:
        delta = 0
        for s in range(n_states):
            old_v = V[s]
            V[s] = eval_state_action(V, s, policy[s])
            delta = max(delta, np.abs(old_v - V[s]))
        if delta < epsilon:
            break

In [121]:
def policy_improvement(V, policy):
    policy_stable = True
    for s in range(n_states):
        old_a = policy[s]
        policy[s] = np.argmax( [eval_state_action(V, s, a) for a in range(n_actions)] )
        if old_a != policy[s]:
            policy_stable = False
    return policy_stable

In [139]:
def run_episodes_PI(env, V, policy, num_games = 1000):
    tot_rew = 0
    state = env.reset()
    for _ in range(num_games):
        done = False
        while not done:
            next_state, reward, done, _ = env.step(policy[state])
            state = next_state
            tot_rew += reward 
            if done:
                state = env.reset()
    print("Won ", tot_rew, " of ", num_games, " games")

In [140]:
# Make the main cycle to do 1 step of policy evaluation and 1 step of policy improvement
policy_stable = False
iteration = 0
while not policy_stable:
    policy_evaluation(V, policy)
    policy_stable = policy_improvement(V, policy)
    iteration += 1

In [142]:
print("Converged after iteration:", iteration)
run_episodes_PI(env, V, policy)
print(V.reshape((4,4))) # Make game board 
print(policy.reshape((4,4))) # Game board size 


Converged after iteration: 1
Won  836.0  of  1000  games
[[0.54118851 0.49768315 0.46938028 0.45543752]
 [0.55770637 0.         0.35778072 0.        ]
 [0.59119068 0.64264127 0.6148228  0.        ]
 [0.         0.74141828 0.8626849  0.        ]]
[[0. 3. 3. 3.]
 [0. 0. 0. 0.]
 [3. 1. 0. 0.]
 [0. 2. 1. 0.]]


In [148]:
def value_iteration(epsilon = 0.0001):
    iteration = 0
    while True:
        delta = 0
        # Update value for each state 
        for s in range(n_states):
            old_v = V[s]
            V[s] = np.max([eval_state_action(V, s, a) for a in range(n_actions)])
            delta = max(delta, np.abs(old_v - V[s]))
        # When stable, break
        if delta < epsilon:
            break
        else:
            print("Iteration:", iteration, "Delta: ", np.round(delta,5))
        iteration += 1
    return V

In [152]:
def run_episodes_VI(env, V, num_games = 100):
    tot_rew = 0
    state = env.reset()
    
    for _ in range(num_games):
        done = False
        
        while not done:
            action = np.argmax([eval_state_action(V, state, a) for a in range(n_actions)])
            next_state, reward, done, _ = env.step(action)
            state = next_state
            tot_rew += reward 
            if done:
                state = env.reset()
    print("Won ", tot_rew, " of ", num_games, " games")

In [153]:
V = value_iteration(epsilon = 0.0001)

run_episodes_VI(env, V, 1000)

print(V.reshape((4,4)))


Won  808.0  of  1000  games
[[0.54133406 0.49787996 0.46961266 0.45568792]
 [0.55783594 0.         0.35788083 0.        ]
 [0.5912967  0.64271799 0.61489039 0.        ]
 [0.         0.74147114 0.86271159 0.        ]]
